
import { Inter } from "next/font/google"; // ✅ 'Inter' capital I se
import "./globals.css";
import { RegFormProvider } from "./usestate";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
       <RegFormProvider>
        {children}
        </RegFormProvider> 
      </body>
    </html>
  );
}
